name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kaniko
        run: |
          mkdir -p /kaniko/.docker
          echo '{"auths":{"https://index.docker.io/v1/":{"auth":"$(echo -n ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} | base64)"}}}' > /kaniko/.docker/config.json

      - name: Build and push Docker image with Kaniko
        uses: gcr.io/kaniko-project/executor:latest
        with:
          args: --context . --destination ${{ secrets.DOCKER_USERNAME }}/testKaniko:latest
        env:
          DOCKER_CONFIG: /kaniko/.docker
